### ISSUE TITLE
Fix path for Junit test results

### ISSUE THREAD

**Issue by jesseborden** [bordenitllc/ubi-container-hardening#4]
Path is probably incorrect for publishing, as not publishing results properly.

**Comment by jesseborden** [comment]
See:
https://github.com/bordenitllc/ubi-container-hardening/pull/2/checks?check_run_id=22221936939

**Comment by bordenit** [comment]
#9

**Comment by bordenit** [comment]
It was strange quote behavior. Action was putting begin and end quote in the file path. Removed quotes from string and it works again.
